- name: add ssh key for david
  authorized_key:
    user: david
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILlo1w1sVinYpsBOIetsVJQ1gkxoqyQ6YAUmmXz2+NgW ansible" 


- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
